export const INVOKE_CHANNELS = [
  'keys:status',
  'keys:set',
  'keys:test',
  'keys:encryption-available',
  'search:symbols',
  'quote:get',
  'profile:get',
  'peers:get',
  'metric:get',
  'candles:get',
  'earnings:get',
  'news:get',
  'news:sentiment',
  'metric:full',
  'fundamentals:statements',
  'fundamentals:peers',
  'earnings:full',
  'dividends:get',
  'filings:get',
  'calendar:get',
  'insider:latest',
  'wire:get',
  'space:get',
  'flights:get',
  'options:flow',
  'social:get',
  'screener:run',
  'screener:screens',
  'screener:save-screen',
  'screener:delete-screen',
  'portfolio:list',
  'portfolio:save',
  'portfolio:create',
  'portfolio:delete',
  'portfolio:export',
  'portfolio:import',
  'alerts:state',
  'alerts:save-rule',
  'alerts:delete-rule',
  'alerts:mark-seen',
  'alerts:clear-log',
  'macro:series',
  'macro:releases',
  'eco:earnings-week',
  'yields:get',
  'fx:pairs',
  'crypto:markets',
  'crypto:detail',
  'stream:subscribe',
  'stream:unsubscribe',
  'stream:state',
  'ratelimit:status',
  'watchlist:list',
  'watchlist:save',
  'watchlist:create',
  'watchlist:delete',
  'wei:international',
  'wei:sparkline',
  'movers:get',
  'notes:list',
  'notes:get',
  'notes:save',
  'notes:delete',
  'settings:get',
  'settings:set',
  'settings:cache-stats',
  'settings:clear-caches',
  'workspace:load',
  'workspace:save',
  'workspace:switch',
  'workspace:delete',
  'workspace:list',
  'workspace:export',
  'workspace:import',
  'panel:popout',
  'popout:init',
  'popout:update',
  'popout:remove',
  'link:set-ticker',
  'panel:snapshot',
  'export:csv',
  'export:json',
  'options:expirations',
  'options:chain',
  'update:state',
  'update:download',
  'update:install',
  'update:simulate',
  'logs:open',
  'diagnostics:export',
  'app:version'
] as const

export type InvokeChannel = (typeof INVOKE_CHANNELS)[number]

export const SEND_CHANNELS = ['win:minimize', 'win:toggle-maximize', 'win:close', 'win:close-self'] as const
export type SendChannel = (typeof SEND_CHANNELS)[number]

/** main → renderer push channels the preload will expose via terminal.on() */
export const EVENT_CHANNELS = [
  'stream:ticks',
  'stream:state',
  'ratelimit:status',
  'alerts:fired',
  'alerts:open-log',
  'popout:returned',
  'link:ticker',
  'update:status',
  'system:resumed'
] as const
export type EventChannel = (typeof EVENT_CHANNELS)[number]
