import { useSyncExternalStore } from 'react'
import type { AlertLogEntry, AlertSound } from '../../../shared/types'
import soundDefault from '../assets/sounds/alert-default.wav'
import soundUrgent from '../assets/sounds/alert-urgent.wav'

/**
 * Renderer-side alert plumbing: unseen-badge count for the status bar and a
 * short beep when a rule fires while the window is visible (the OS
 * notification covers the hidden case). Sound toggle lives in SET (Batch C);
 * default on, soft.
 */

let unseen = 0
const listeners = new Set<() => void>()

function notify(): void {
  listeners.forEach((fn) => fn())
}

export function setUnseen(count: number): void {
  unseen = count
  notify()
}

export function useAlertUnseen(): number {
  return useSyncExternalStore(
    (onChange) => {
      listeners.add(onChange)
      return () => listeners.delete(onChange)
    },
    () => unseen
  )
}

/**
 * Bundled terminal-style beeps (generated by scripts/generate-sounds.js, public
 * domain). Plays in the main-window renderer even while the window is hidden
 * to the tray — the window is hidden, not destroyed, so audio still works.
 */
function playAlertSound(sound: AlertSound): void {
  if (sound === 'none') return
  if (window.localStorage.getItem('alert-sound') === 'off') return
  try {
    const audio = new Audio(sound === 'urgent' ? soundUrgent : soundDefault)
    const volume = Number(window.localStorage.getItem('alert-volume') ?? '0.5')
    audio.volume = Number.isFinite(volume) ? Math.min(1, Math.max(0, volume)) : 0.5
    void audio.play().catch(() => undefined)
  } catch {
    /* audio unavailable */
  }
}

window.terminal.on('alerts:fired', (payload) => {
  const p = payload as { entry: AlertLogEntry; unseen: number; sound?: AlertSound }
  unseen = p.unseen
  notify()
  playAlertSound(p.sound ?? 'default')
})
