import { useState } from 'react'
import type { WorkbenchState } from '../../../../shared/paper/workbench'
import { actionSchema } from '../../../../shared/paper/management'
import type { CorporateAction } from '../../../../shared/paper/types'
import { usePaperAction } from '../hooks/usePaper'
import { decimalUnits,nyTime,useNavigation } from '../state'
import { money,runName } from '../presentation'
import Confirm from '../components/Confirm'
import { useHistory } from './DetailPage'
function Review({id,state}:{id:string;state:WorkbenchState}):JSX.Element {
  const history=useHistory(id),action=usePaperAction(),[confirm,setConfirm]=useState(false),navigate=useNavigation(s=>s.navigate)
  const run=state.runs.find(r=>r.id===id)!,disabled=state.halted||state.restorePending||action.isPending
  return <section className="wb-card"><h2>{runName(run)}</h2><p>涉及标的：{run.config.symbols.join('、')}</p>{history.isPending&&<p>读取核对状态中…</p>}{history.isError&&<p role="alert">核对状态读取失败 <button onClick={()=>void history.refetch()}>重试</button></p>}{history.data&&<p className={history.data.reviewed?'':'wb-warning'}>公司行动：{history.data.reviewed?'用户已核对':'未核对，不代表完整总回报'} · 行情质量记录 {history.data.qualityCount} · 覆盖率 {history.data.coverage.pct?.toFixed(2)??'—'}%</p>}<p>最近活动：{nyTime(state.summaries[id]?.latestEvent?.at)} · {state.summaries[id]?.latestEvent?.reason??'无记录'}</p><div className="wb-row"><button onClick={()=>navigate('detail',id)}>查看完整时间范围、事件与持仓</button><button disabled={disabled||!history.data} onClick={()=>setConfirm(true)}>确认已核对</button></div>{confirm&&<Confirm title="确认公司行动核对" busy={action.isPending} onClose={()=>setConfirm(false)} onConfirm={()=>{if(!disabled)action.mutate({type:'control',id,action:'review'},{onSuccess:()=>setConfirm(false)})}}><p>确认已人工核对 {runName(run)} 截至现在的拆股、股息及现金替代。此标记不会自动补记账，也不会修复缺失行情。</p>{action.error&&<p role="alert">{action.error.message}</p>}</Confirm>}</section>
}
export default function DataPage({state}:{state:WorkbenchState}):JSX.Element {
  const mutation=usePaperAction(),[id,setId]=useState(''),[symbol,setSymbol]=useState(''),[type,setType]=useState('dividend'),[date,setDate]=useState(''),[amount,setAmount]=useState(''),[numerator,setNumerator]=useState(''),[denominator,setDenominator]=useState(''),[cash,setCash]=useState(''),[pending,setPending]=useState<CorporateAction>(),[error,setError]=useState(''),[reviewId,setReviewId]=useState(''),[notice,setNotice]=useState('')
  const disabled=mutation.isPending||state.halted||state.restorePending
  const affected=state.runs.filter(r=>r.config.symbols.includes(pending?.symbol??symbol)&&!['ended','archived'].includes(r.status))
  function prepare():void {
    try {if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2})?Z$/.test(date))throw new Error('请输入带 Z 的 UTC 时间，例如 2026-09-28T14:00:00Z');const parsed=actionSchema.parse({type:'corporate',action:{id,symbol,occurredAt:Date.parse(date),type,...(type==='dividend'?{perShare:decimalUnits(amount,6)}:{numerator:Number(numerator),denominator:Number(denominator),...(cash?{cashInLieuPrice:decimalUnits(cash,6)}:{})})}});if(parsed.type!=='corporate')return;if(parsed.action.occurredAt>Date.now())throw new Error('不能提交未来公司行动');setError('');setPending(parsed.action)}catch(e){setError(String(e))}
  }
  return <><section className="wb-card"><h2>数据与核对</h2><p className="wb-warning">公司行动未核对实例：{state.runs.filter(r=>!state.summaries[r.id]?.reviewed).length}。请逐一选择实例核对。</p><p>实时连接不代表长期覆盖完整。中断、旧价或疑似价格跳变可能使策略跳过或暂停；请查看受影响实例的事件和价格时间，核对后再恢复。</p><p>最新采集：{state.market?`${state.market.symbol} · ${state.market.reason} · ${nyTime(state.market.marketTime)}`:'无记录'}</p><label>选择实例查看核对记录<select value={reviewId} onChange={e=>setReviewId(e.target.value)}><option value="">请选择（含归档历史）</option>{state.runs.map(r=><option key={r.id} value={r.id}>{runName(r)}</option>)}</select></label></section>{state.runs.some(r=>r.id===reviewId)&&<Review key={reviewId} id={reviewId} state={state}/>}
    <section className="wb-card"><h2>人工录入公司行动</h2><p className="wb-warning">按当前持仓记账，不能追溯模拟过去持仓。所有包含该标的的未结束实例会暂停；已结束和归档账户保留终止结果。请及时核对，不自动推断拆股。</p><form onSubmit={e=>{e.preventDefault();prepare()}}><fieldset disabled={disabled}><div className="wb-fields"><label>唯一行动 ID<input required maxLength={100} value={id} onChange={e=>setId(e.target.value)}/></label><label>标的代码<input required value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/></label><label>原始生效时间（UTC，带 Z）<input required placeholder="2026-09-28T14:00:00Z" value={date} onChange={e=>setDate(e.target.value)}/></label><label>行动类型<select value={type} onChange={e=>setType(e.target.value)}><option value="dividend">现金股息</option><option value="split">拆股 / 反向拆股</option></select></label>{type==='dividend'?<label>每股股息 USD<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label>:<><label>新股数<input required type="number" min="1" max="1000000" step="1" value={numerator} onChange={e=>setNumerator(e.target.value)}/></label><label>旧股数<input required type="number" min="1" max="1000000" step="1" value={denominator} onChange={e=>setDenominator(e.target.value)}/></label><label>碎股现金替代价 USD（可选）<input inputMode="decimal" value={cash} onChange={e=>setCash(e.target.value)}/></label></>}</div><button>审阅影响并确认</button></fieldset></form>{error&&<p role="alert" className="wb-error">{error}</p>}{notice&&<p role="status">{notice}</p>}</section>
    {pending&&<Confirm title="暂停相关实例并记账" busy={mutation.isPending} onClose={()=>setPending(undefined)} onConfirm={()=>{if(!disabled)mutation.mutate({type:'corporate',action:pending},{onSuccess:()=>{setPending(undefined);setNotice('公司行动已提交。请查看当前持仓和事件后再决定恢复策略。') }})}}><p>{pending.id} · {pending.symbol} · {nyTime(pending.occurredAt)}</p><p>{pending.type==='dividend'?`每股股息 ${money(pending.perShare)}`:`${pending.numerator} 新股 / ${pending.denominator} 旧股；碎股价 ${pending.cashInLieuPrice==null?'未提供':money(pending.cashInLieuPrice)}`}</p><p>以下实例将暂停并按提交时当前持仓记账；相同行动 ID 防重复。</p>{affected.map(r=><p key={r.id}>{runName(r)} · 当前 {r.account.positions.find(p=>p.symbol===pending.symbol)?.quantity??0} 股</p>)}{!affected.length&&<p>无符合条件的未结束实例，此提交不会调整账户。</p>}{mutation.error&&<p role="alert" className="wb-error">提交未完成：{mutation.error.message}</p>}</Confirm>}
  </>
}
