import { useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import type { WorkbenchState } from '../../../../shared/paper/workbench'
import type { PaperRun,Fill,StrategyEvent } from '../../../../shared/paper/types'
import type { PaperHistory,Valuation } from '../../../../shared/paper/management'
import { invoke } from '../../lib/ipc'
import PaperEquityChart from '../../panels/PaperEquityChart'
import { usePaperAction } from '../hooks/usePaper'
import Confirm from '../components/Confirm'
import { allowedControls,controlText,dateRange,money,percent,qualityText,runName,type Control } from '../presentation'
import { emptyDraft,nyTime,statusText,unitsDecimal,useNavigation } from '../state'
import { DRAFT_KEY } from './CreatePage'
export function useHistory(id:string) {
  return useQuery({queryKey:['paper-history',id],queryFn:()=>invoke<PaperHistory>('paper:history',{id,limit:1}),refetchInterval:60000,refetchIntervalInBackground:false,staleTime:30000})
}
function HistoryPage({id,kind,from,to,active}:{active:boolean;id:string;kind:'fills'|'events'|'snapshots';from:number;to:number}):JSX.Element {
  const [offset,setOffset]=useState(0)
  const query=useQuery({enabled:active,queryKey:['paper-page',id,kind,from,to,offset],queryFn:()=>invoke<{rows:Array<Fill|StrategyEvent|Valuation>;count:number}>('paper:page',{id,kind,from,to,offset,limit:100}),refetchInterval:60000,refetchIntervalInBackground:false})
  const rows=query.data?.rows??[]
  return <section className="wb-card"><h2>{{fills:'成交',events:'活动与中断',snapshots:'净值采样'}[kind]}</h2>{query.isPending&&<p role="status">读取中…</p>}{query.isError&&<p role="alert">读取失败：{query.error.message}<button onClick={()=>void query.refetch()}>重试</button></p>}{query.data&&<><div className="wb-row"><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-100))}>上一页</button><span>第 {offset/100+1} 页 · 共 {query.data.count} 条</span><button disabled={offset+100>=query.data.count} onClick={()=>setOffset(offset+100)}>下一页</button></div>{!rows.length&&<p>所选区间暂无记录。</p>}{kind==='snapshots'&&<PaperEquityChart label="当前分页持久净值 USD（不代表完整历史）" series={[{id,points:(rows as Valuation[]).map(s=>({at:s.at,value:s.equity===null?null:s.equity/1e6,fresh:s.quality==='fresh'}))}]}/>}<div className="wb-table"><table><thead><tr><th>纽约时间</th><th>内容</th><th>详情</th></tr></thead><tbody>{rows.map(row=>{if('eventId'in row)return <tr key={row.eventId}><td>{nyTime(row.occurredAt)}</td><td>{row.type} · {row.reason}</td><td><details><summary>高级原值</summary><pre>{JSON.stringify(row.summary,null,2)}</pre></details></td></tr>;if('side'in row)return <tr key={row.id}><td>{nyTime(row.marketTime)}</td><td>{row.symbol} · {row.side==='buy'?'买入':'卖出'} {row.quantity} 股</td><td>{money(row.price)} / 股 · 费用 {money(row.fee)}</td></tr>;return <tr key={row.at}><td>{nyTime(row.at)}</td><td>{money(row.equity)} · {qualityText[row.quality]}</td><td>{Object.entries(row.prices).map(([symbol,p])=><p key={symbol}>{symbol} {money(p.price)} · {nyTime(p.at)}</p>)}</td></tr>})}</tbody></table></div></>}</section>
}
export function Metrics({data}:{data:PaperHistory}):JSX.Element {
  return <><p>观察 {(data.observedMs/3600000).toFixed(2)} 小时 · 新鲜 bar 覆盖率 {percent(data.coverage.pct)}（{data.coverage.fresh} / {data.coverage.expected<0?'日历未覆盖':data.coverage.expected} 标的分钟，包含暂停时段）</p><dl className="wb-stat-grid"><div><dt>成本后收益</dt><dd>{percent(data.performance.returnPct)}</dd></div><div><dt>总盈亏</dt><dd>{money(data.performance.totalPnl)}</dd></div><div><dt>分钟采样最大回撤</dt><dd>{percent(data.performance.maxDrawdownPct)}</dd></div><div><dt>完整平仓样本</dt><dd>{data.performance.closedTrades}<small> 笔</small></dd></div></dl><p className="wb-warning">{data.performance.incomplete?'数据不完整；请结合中断与覆盖率判断。':'请结合覆盖率判断。'} 公司行动：{data.reviewed?'用户已核对':'未核对，不代表完整总回报'} · 行情质量记录 {data.qualityCount}</p><details><summary>日 / 月收益（纽约日期）</summary><div className="wb-table"><table><thead><tr><th>期间</th><th>收益</th><th>完整性</th></tr></thead><tbody>{[...data.performance.days,...data.performance.months].map(p=><tr key={p.period}><td>{p.period}</td><td>{percent(p.returnPct)}</td><td>{p.incomplete?'不完整（首末期或缺口）':'完整'}</td></tr>)}</tbody></table></div></details></>
}
export default function DetailPage({run,state}:{run:PaperRun;state:WorkbenchState}):JSX.Element {
  const pending=useRef(false),action=usePaperAction(),metrics=useHistory(run.id),navigate=useNavigation(s=>s.navigate)
  const [confirm,setConfirm]=useState<Control>(),[from,setFrom]=useState(''),[to,setTo]=useState(''),[tab,setTab]=useState<'fills'|'events'|'snapshots'>('fills'),[copyError,setCopyError]=useState('')
  const value=state.valuations[run.id],allowed=allowedControls(run,state)
  let range:{from:number;to:number}|undefined,rangeError='';try{range=dateRange(from,to)}catch(e){rangeError=String(e)}
  const perform=(control:Control):void=>{if(pending.current||!allowed.includes(control))return;pending.current=true;action.mutate({type:'control',id:run.id,action:control},{onSuccess:()=>setConfirm(undefined),onSettled:()=>{pending.current=false}})}
  return <><section className="wb-card"><h2>{runName(run)}</h2><p>{statusText[run.status]} · {run.config.symbols.join('、')} · {value?qualityText[value.quality]:'尚无估值'}</p>{state.summaries[run.id]?.liquidating&&<p className="wb-warning">正在等待清仓新价，最多 60 秒。失败或超时可能保留仓位；这不会恢复策略运行。</p>}<div className="wb-row">{(['start','pause','liquidate','end','archive'] as Control[]).map(c=><button key={c} disabled={action.isPending||!allowed.includes(c)} onClick={()=>c==='start'||c==='pause'?perform(c):setConfirm(c)}>{controlText[c]}</button>)}<button onClick={()=>{try{const template=state.templates.find(t=>t.kind===run.config.strategyVersion.split(':')[0]);if(!template)throw new Error('当前模板不可用');localStorage.setItem(DRAFT_KEY,JSON.stringify({...emptyDraft,template:template.id,symbols:run.config.symbols,parameters:Object.fromEntries(Object.entries(run.config.parameters).map(([k,v])=>[k,String(v)])),cash:unitsDecimal(run.config.initialCash,6),fee:unitsDecimal(run.config.fee,6),slippage:String(run.config.slippageBps),position:unitsDecimal(run.config.maxPositionBps,2)}));navigate('create')}catch(e){setCopyError(String(e))}}}>复制为新实例</button></div><p className="wb-muted">创建不启动。复制使用当前模板版本并重新审阅。清仓仅限交易时段；归档后不能清仓。操作结果以最新账户状态为准。</p>{(action.error||copyError)&&<p role="alert" className="wb-error">操作未完成：{action.error?.message||copyError}</p>}<dl className="wb-stat-grid"><div><dt>账户净值</dt><dd>{money(value?.equity)}</dd></div><div><dt>可用现金</dt><dd>{money(run.account.cash)}</dd></div><div><dt>已实现盈亏</dt><dd>{money(run.account.realizedPnl)}</dd></div><div><dt>未实现盈亏</dt><dd>{money(value?.unrealized)}</dd></div><div><dt>现金收益</dt><dd>{money(run.account.income)}</dd></div></dl><details><summary>冻结配置 / 版本与高级详情</summary><p>初始本金 {money(run.config.initialCash)} · 每单费用 {money(run.config.fee)} · 滑点 {run.config.slippageBps} bps</p><pre>{JSON.stringify(run.config,null,2)}</pre></details></section>
    <section className="wb-card wb-table"><h2>当前持仓</h2>{!run.account.positions.length?<p>暂无持仓。</p>:<table><thead><tr><th>标的</th><th>股数</th><th>总成本 USD</th><th>估值价 / 时间</th></tr></thead><tbody>{run.account.positions.map(p=><tr key={p.symbol}><td>{p.symbol}</td><td>{p.quantity}</td><td>{money(p.cost)}</td><td>{money(value?.prices[p.symbol]?.price)} · {nyTime(value?.prices[p.symbol]?.at)}</td></tr>)}</tbody></table>}</section>
    <section className="wb-card"><h2>完整观察期绩效</h2><p className="wb-muted">从创建至最近采样；与下方分页和日期筛选独立。费用及滑点已进入账本，展示下采样不参与指标计算。</p>{metrics.isPending&&<p>读取指标中…</p>}{metrics.isError&&<p role="alert">指标读取失败 <button onClick={()=>void metrics.refetch()}>重试</button></p>}{metrics.data&&<Metrics data={metrics.data}/>}<button onClick={()=>navigate('data')}>进入公司行动核对</button></section>
    <section className="wb-card"><h2>历史筛选（纽约日期，包含截止日）</h2><div className="wb-fields"><label>开始日期<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>截止日期<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="wb-row">{(['fills','events','snapshots'] as const).map(k=><button aria-pressed={tab===k} key={k} onClick={()=>setTab(k)}>{{fills:'成交',events:'活动',snapshots:'净值'}[k]}</button>)}</div>{rangeError&&<p role="alert">{rangeError}</p>}</section>
    {range&&(['fills','events','snapshots'] as const).map(k=><div hidden={tab!==k} key={k}>{<HistoryPage active={tab===k} key={`${run.id}:${k}:${from}:${to}`} id={run.id} kind={k} {...range}/>}</div>)}
    {confirm&&<Confirm title={controlText[confirm]} busy={action.isPending} onClose={()=>setConfirm(undefined)} onConfirm={()=>{if(allowed.includes(confirm))perform(confirm)}}><p>{runName(run)} · 当前 {statusText[run.status]}</p><p>持仓：{run.account.positions.map(p=>`${p.symbol} ${p.quantity} 股`).join('、')||'无'}</p><p>{confirm==='liquidate'?'暂停策略并等待新鲜价格清仓，最多等待 60 秒；可能部分成交或保留仓位。暂停 / 已结束账户不会因此恢复策略。':confirm==='end'?'结束后不能恢复策略，当前持仓保留；如需清仓须另行请求。':'归档保留账本和历史，但之后不能请求清仓。请先核对剩余持仓及成交。'}</p>{!allowed.includes(confirm)&&<p role="alert">状态已变化，此操作当前不可用，请取消后重新检查。</p>}{action.error&&<p role="alert">{action.error.message}</p>}</Confirm>}
  </>
}
