import { useRef, useState } from 'react'
import type { WorkbenchState } from '../../../../shared/paper/workbench'
import { symbolSchema } from '../../../../shared/paper/schemas'
import { usePaperAction } from '../hooks/usePaper'
import { nyTime, useNavigation } from '../state'
export default function InstrumentsPage({ state }: { state: WorkbenchState }): JSX.Element {
  const [symbol,setSymbol] = useState(''), [kind,setKind] = useState<'stock'|'etf'>('stock'), [error,setError] = useState('')
  const action = usePaperAction(), pending = useRef(false)
  async function submit(payload: unknown): Promise<void> { if (pending.current) return; pending.current = true; setError(''); try { await action.mutateAsync(payload); setSymbol('') } catch(e) { setError(e instanceof Error ? e.message : '操作失败') } finally { pending.current = false } }
  return <><section className="wb-card"><h2>手选标的 · {state.instruments.length} / 10</h2><p className="wb-muted">来源 Alpaca · raw IEX。ETF 类型由你选择，资产接口仅验证可交易的美股，不自动选股。</p><form className="wb-row" onSubmit={e => { e.preventDefault(); const value = symbol.trim().toUpperCase(); if (!symbolSchema.safeParse(value).success) { setError('请输入有效证券代码'); return } if (state.instruments.some(i=>i.symbol===value)) { setError('该标的已在池中'); return } void submit({type:'add',symbol:value,kind}) }}><label>证券代码<input value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="例如 AAPL / SPY" required maxLength={15}/></label><label>类型<select value={kind} onChange={e=>setKind(e.target.value as 'stock'|'etf')}><option value="stock">股票</option><option value="etf">ETF</option></select></label><button className="primary" disabled={action.isPending || state.instruments.length >= 10 || state.halted || state.restorePending}>{action.isPending ? '正在验证/处理…' : '验证并添加'}</button></form>{error && <p role="alert" className="wb-error">{error}。请检查代码、凭证与权限后重试。</p>}</section><section className="wb-card wb-table"><table><thead><tr><th>标的</th><th>类型</th><th>使用情况</th><th>操作</th></tr></thead><tbody>{state.instruments.map(i=>{ const owners=state.runs.filter(r=>r.status!=='archived' && r.config.symbols.includes(i.symbol)); return <tr key={i.symbol}><td>{i.symbol}</td><td>{i.kind==='etf'?'ETF':'股票'}</td><td>{owners.length ? owners.map(r=><button key={r.id} onClick={()=>useNavigation.getState().navigate('detail',r.id)}>{r.config.strategyVersion.split(':')[0]} · {r.id.slice(0,8)}</button>):'未被使用'}</td><td><button disabled={!!owners.length || action.isPending || state.halted || state.restorePending} title={owners.length ? '使用中的实例（含已结束未归档）占用此标的' : '移除标的'} onClick={()=>void submit({type:'remove',symbol:i.symbol})}>移除</button></td></tr>})}</tbody></table>{!state.instruments.length && <p>尚未选择标的。添加股票或 ETF 后即可创建策略。</p>}<p className="wb-muted">最近采集记录：{state.market ? `${state.market.symbol} · ${state.market.reason} · ${nyTime(state.market.marketTime)}` : '无最近记录'}。这不是每个标的的实时价格。</p></section></>
}
