import { useState } from 'react'
import type { WorkbenchState } from '../../../../shared/paper/workbench'
import { nyTime,statusText,useNavigation } from '../state'
import { money,needsAttention,percent,qualityText,runName,reasonSummary } from '../presentation'
export default function OverviewPage({state}:{state:WorkbenchState}):JSX.Element {
  const navigate=useNavigation(s=>s.navigate),[filter,setFilter]=useState('all')
  const attention=state.runs.filter(r=>needsAttention(r,state)),active=state.runs.filter(r=>['running','warming','data_insufficient'].includes(r.status))
  const runs=state.runs.filter(r=>filter==='all'||(filter==='attention'?needsAttention(r,state):r.status===filter))
  const events=state.runs.flatMap(r=>state.summaries[r.id]?.latestEvent?[{run:r,event:state.summaries[r.id].latestEvent!}]:[]).sort((a,b)=>b.event.at-a.event.at).slice(0,10)
  return <><section className="wb-card wb-row"><div>运行 / 预热实例 <strong>{active.length}</strong></div><div>需查看实例 <strong>{attention.length}</strong></div><div>已选标的 <strong>{state.instruments.length} / 10</strong></div></section>
    {!state.configured&&<section className="wb-card"><h2>连接模拟行情</h2><p>尚未配置 Alpaca；历史仍可查看，启动前请保存凭证并检查权限。</p><button onClick={()=>navigate('settings')}>配置行情</button></section>}
    {!state.runs.length?<section className="wb-card"><h2>创建首个策略</h2><p>连接行情 → 手选最多 10 个标的 → 创建并审阅 → 单独启动。</p><button onClick={()=>navigate('instruments')}>选择标的</button></section>:<section className="wb-card wb-table"><label>账户筛选<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部（含归档历史）</option><option value="attention">需要查看</option>{Object.entries(statusText).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{!active.length&&<p className="wb-muted">当前没有运行或预热中的实例。可查看历史，或进入详情启动可恢复的实例。</p>}<table><thead><tr><th>实例 / 标的</th><th>账户 / 操作</th><th>净值 USD</th><th>成本后收益</th><th>最近采样 / 观察跨度</th><th>数据质量</th></tr></thead><tbody>{runs.map(r=>{const v=state.valuations[r.id],s=state.summaries[r.id];return <tr key={r.id}><td><button onClick={()=>navigate('detail',r.id)}>{runName(r)}</button><p>{r.config.symbols.join('、')}</p></td><td>{statusText[r.status]}{s?.liquidating&&<p className="wb-warning">清仓等待新价</p>}</td><td className="wb-number">{money(v?.equity)}</td><td className="wb-number">{percent(v?.equity==null?null:(v.equity/r.config.initialCash-1)*100)}</td><td>{nyTime(s?.latestSampleAt)}<p>{s?.createdAt!=null&&s.latestSampleAt!=null?`${(Math.max(0,s.latestSampleAt-s.createdAt)/3600000).toFixed(2)} 小时`:'暂无观察'}</p></td><td>{v?qualityText[v.quality]:'尚无估值'}{!s?.reviewed&&<p className="wb-warning">公司行动未核对</p>}</td></tr>})}</tbody></table>{!runs.length&&<p>没有符合条件的实例。</p>}<p className="wb-muted">每个实例为独立账户；不同起点收益不构成排名。观察时长、完整覆盖率和公司行动核对见详情。</p></section>}
    <section className="wb-card"><h2>待处理与最近活动</h2>{state.halted&&<p className="wb-error">账本或服务已停止，操作受限。请保留账本并检查诊断日志。</p>}{state.session==='unknown'&&<p className="wb-warning">日历范围未知，不能确认交易时段。请检查支持年份。</p>}{!events.length&&<p>暂无活动记录。</p>}{events.map(({run,event})=><div className="wb-activity" key={run.id}><button onClick={()=>navigate('detail',run.id)}>{runName(run)}</button> {statusText[run.status]} · {nyTime(event.at)}<p>{reasonSummary(event.reason)}</p><details><summary>原因码</summary>{event.type} · {event.reason}</details></div>)}<button onClick={()=>navigate('data')}>查看数据问题与公司行动核对</button></section></>
}
